### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by trpjxrdf** [mhzed/wstunnel#31]
Currently each port must be tunneled separetely. Proxy like HTTPS (CONNECT method) or SOCKS5 allowes dynamic selection of the target address and port by the client application.
Would you provide the Socks5 or HTTPS proxy support?

**Comment by mhzed** [comment]
What I usually do is to setup wstunnel so that I can SSH over it, then uses standard SSH command for SOCKS5 proxy.  I.e. in my ~/.ssh/config, I have

Host server.via.wstunnel
    Hostname my.ssh.server.com
    User ubuntu
    ProxyCommand wstunnel -c -t stdio:%h:%p https://my.ws.tunnel.server

Then you can just "ssh server.via.wstunnel" and all the fancy pants stuff you can do with SSH such as SOCKS5 proxy via "-D".

But to answer your question directly:  no I don't plan to offer Socks5 or CONNECT support, because it's not what wstunnel is for, which is to bypass strict firewalls with pack level inspection.  Once bypassed, you can layer other tunnels on top of it (openvpn works also) to achieve other goals.
